spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: ''
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        timezone.default_storage: NORMALIZE # 3.x ???? ???? DEFAULT(UTC) ? ???? NORMALIZE(JVM ?? ??) ???.
        format_sql: true
        use_sql_comments: true
        show_sql: true # ? ??? SQL ?? ??? ?????.
  h2:
    console:
      enabled: true
      path: /h2-console
  cloud:
    config:
      enabled: false

logging:
  level:
    org.hibernate.SQL: DEBUG # Hibernate SQL ??? DEBUG ??? ??
    org.hibernate.type: TRACE # Hibernate ?? ??? TRACE ??? ??
